### ISSUE TITLE
Undefined path for login from admin front page

### ISSUE THREAD

**Issue by CaptEmulation** [nitrogenjs/admin#25]
This bug is on https://admin.nitrogen.io right now.

Reproduction:
 1. Go to https://admin.nitrogen.io
 1. Click on `Sign In` button in top right
 
![image](https://cloud.githubusercontent.com/assets/4467892/8835288/c0257bb6-3076-11e5-8c09-56b9e4c81899.png)

 You end up at a 404 page `https://admin.nitrogen.io/undefined/login`:

![image](https://cloud.githubusercontent.com/assets/4467892/8835315/f4e1e524-3076-11e5-96a7-44232f1fb0c9.png)

**Comment by timfpark** [comment]
Sorry - should be fixed now!

**Comment by CaptEmulation** [comment]
Much better :+1:
